# Generated by Django 3.1.10 on 2025-09-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_auto_20250305_0552'),
        ('profile', '0015_auto_20250320_0959'),
    ]

    operations = [
    ]
